### ISSUE TITLE
cant run the demo file on windows with visual studio code without getting an error 

### ISSUE THREAD

**Issue by Linuxuser1234** [phollemans/vertigo#1]

**Comment by phollemans** [comment]
Can you provide the error that you encountered?

**Comment by Linuxuser1234** [comment]
@phollemans  it showed code language not supported or defined

**Comment by Linuxuser1234** [comment]
Sorry for the late reply

**Comment by Linuxuser1234** [comment]
@phollemans did you find a solution

**Comment by phollemans** [comment]
No, I haven't seen that error in testing.  Are you trying to run on Windows after installing from the vertigo_windows-x64_0_7_556.exe file, or are you trying run the software from source using the gradle build scripts?  Can you provide a screen capture or a video capture of when the error happens?  Are you running Windows 10?  Please provide a step-by-step of what you did in order for us to diagnose the problem.  Describe what you mean by "with visual studio code".

**Comment by Linuxuser1234** [comment]
@phollemans I dint see a exe file

**Comment by awipslinuxuser** [comment]
Ps I got the app working
